name: TWS CI Workflow

on:
    push:
        
jobs:
    build:  # job ka naam
        runs-on: ubuntu-latest # GitHub Runner (Free)
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4 # clone the code into a ubuntu runner

            - name: Setup Docker
              uses: docker/setup-buildx-action@v4